code/AdvisementManager/StudentAdvisementManagerWebApp/Controllers/AdvisementSessionController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Diagnostics;
using System.Linq;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using AdvisementManagerSharedLibrary.Models;
using AdvisementManagerSharedLibrary.Data;
using AdvisementManagerSharedLibrary.DAL;
using System.Collections.Generic;
using StudentAdvisementManagerWebApp.Resources;

namespace StudentAdvisementManagerWebApp.Controllers
{
    /// <summary>
    ///   The Schedule advisement session controller class
    /// </summary>
    public class AdvisementSessionController : Controller
    {
        private readonly string departmentAdvisementHoldReason = "need to meet with dept advisor";

        private readonly string facultyAdvisementHoldReason = "need to meet with faculty advisor";

        private Student student;

        public ApplicationDbContext context { get; }

        private readonly AdvisementSessionDAL sessionDal = new();
        private readonly StudentDal studentDal = new();
        private readonly AdvisorDAL advisorDal = new();
        private readonly HoldDAL holdDal = new();
        private readonly NotificationMailer mailer = new();
        private readonly NotificationDAL notificationDal;

        /// <summary>Initializes a new instance of the <see cref="AdvisementSessionController" /> class.</summary>
        /// <param name="context">The context.</param>
        public AdvisementSessionController(ApplicationDbContext context)
        {

            this.context = context;
            ViewBag.InvalidInputMessage = String.Empty;
            notificationDal = new NotificationDAL(context);
        }

        /// <summary>Schedules the advisement session asynchronous.</summary>
        /// <param name="studentid">The studentid.</param>
        /// <param name="holdreason">The holdreason.</param>
        /// <param name="generaladvisorid">The generaladvisorid.</param>
        /// <param name="facultyadvisorid">The facultyadvisorid.</param>
        /// <returns>
        ///   The view to the schedule advisement session
        /// </returns>
        public IActionResult ScheduleAdvisementSession(int studentid, string holdreason, int generaladvisorid, int facultyadvisorid, string selecteddate)
        {
            Trace.WriteLine("Date was: " + selecteddate);
            ScheduleAdvisementModel model = InitializeScheduleAdvismentModel(studentid, selecteddate);

            return View("../AdvisementSession/ScheduleAdvisementSession", model);
        }

        /// <summary>
        ///     Initializes the schedule advisment model. 
        ///     Determines which advisor the student must meet with and gets there available times to display.
        /// </summary>
        /// <param name="student">The student.</param>
        /// <param name="holdreason">The holdreason.</param>
        /// <returns>
        ///   The schedule model
        /// </returns>
        private ScheduleAdvisementModel InitializeScheduleAdvismentModel(int studentId, string date)
        {
            ScheduleAdvisementModel scheduleModel = new ScheduleAdvisementModel();
            AvailabilityDAL availDal = new AvailabilityDAL();

            this.student = this.studentDal.ObtainStudentWithId(studentId, this.context);

            scheduleModel.Student = student;

            if (student.Hold.Reason == this.departmentAdvisementHoldReason)
            {
                scheduleModel.Advisor = scheduleModel.Student.GeneralAdvisor;
            }
            else if (student.Hold.Reason == this.facultyAdvisementHoldReason)
            {
                scheduleModel.Advisor = scheduleModel.Student.FacultyAdvisor;
            }
            else
            {
                Debug.Print("Must add students that have standard reasons");
                scheduleModel.Advisor = scheduleModel.Student.GeneralAdvisor;
            }
            List<Availability> times = availDal.GetAdvisorAvailability(scheduleModel.Advisor.Id, this.context);
            //scheduleModel.SetAvailableSessionTimesListItems(scheduleModel.Student.GeneralAdvisor);

            scheduleModel.SetAvailabilities(times, date);
            return scheduleModel;
        }

            /// <summary>
            ///     Confirms the appointment is scheduled for a valid time and date,
            ///     returns Schedule view if not, schedules session on the database if so.
            /// </summary>
            /// <param name="studentid">The studentid.</param>
            /// <param name="advisorid">The advisorid.</param>
            /// <param name="date">The date.</param>
            /// <param name="time">The time.</param>
            /// <returns>
            ///     Redirections to the student home page, or
            ///     return Schedule view to get new dateTime.
            /// </returns>
            public IActionResult ConfirmAppointment(int? studentid, int? advisorid, DateTime date, TimeSpan time)
        {
            var sessionTime = date.AddMinutes(time.TotalMinutes);

            Advisor advisor = advisorDal.ObtainAdvisorWithId((int)advisorid, this.context);
            Student student = studentDal.ObtainStudentWithId((int)studentid, this.context);

            if (IsSessionTimeInTheFuture(sessionTime))
            {
                this.ScheduleSession(studentid.Value, advisorid.Value, sessionTime);

                Notification notification = new()
                {
                    AdvisorId = (int)advisorid,
                    StudentId = (int)studentid,
                    NotifMessage = ConstantManager.GetCreatedAppointmentMeetingMessage(date) 
                                                    + student.FirstName + " " + student.LastName 
                                                    + " is meeting with " + advisor.FirstName 
                                                    + " " + advisor.LastName + "."
                };

                this.notificationDal.AddNotification(notification.NotifMessage, notification.StudentId, notification.AdvisorId, this.context);
                this.mailer.SendEmailNotification(advisor, student, notification);

                return RedirectToAction("StudentHome", "Home");
            }

            ScheduleAdvisementModel scheduleModel = InitializeScheduleAdvismentModel(studentid.Value, date.ToString());

            ViewBag.InvalidInputMessage = "The appointment time cannot be in the past.";

            return View("../AdvisementSession/ScheduleAdvisementSession", scheduleModel);
        }

        /// <summary>Determines if the appointment time is in the future</summary>
        /// <param name="sessionTime">The date of the session.</param>
        /// <returns>
        ///   bool, if the sessionTime is in the future or not.
        /// </returns>
        private bool IsSessionTimeInTheFuture(DateTime sessionTime)
        {
            return DateTime.Compare(sessionTime, DateTime.Now) > 0;
        }

        /// <summary>Schedules the advisement session to the database.</summary>
        /// <param name="studentid">The studentid.</param>
        /// <param name="advisorid">The advisorid.</param>
        /// <param name="sessionTime">The date of the session.</param>
        private void ScheduleSession(int studentId, int advisorId, DateTime sessionTime)
        {
            AdvisementSession session = new AdvisementSession
            {
                StudentId = studentId,
                AdvisorId = advisorId,
                Date = sessionTime,
                Completed = false,
                HoldId = this.holdDal.ObtainHold(studentId, this.context).Id
            };
            this.sessionDal.ScheduleAdvisementSession(session, this.context);
        }

        /// <summary>Displays a view showing a list of the students previous sessions from this semester</summary>
        /// <param name="id">The asession id.</param>
        /// <returns>
        ///   The view to the advisement sessions list
        /// </returns>
        public IActionResult AdvisementSessions(int? studentid, int? holdid)
        {
            var studentsSessions = this.sessionDal.ObtainPastSessionsFromIDs(this.context, studentid.Value, holdid.Value);

            foreach (var session in studentsSessions)
            {
                session.Advisor = this.advisorDal.ObtainAdvisorWithId(session.AdvisorId, this.context);
            }

            return View(studentsSessions);
        }

        /// <summary>Displays an advisement session</summary>
        /// <param name="id">The asession id.</param>
        /// <returns>
        ///   The view to the advisement session
        /// </returns>
        public IActionResult AdvisementSession(int? id)
        {
            var session = this.sessionDal.ObtainSessionFromId(id, this.context);
            session.Advisor = this.advisorDal.ObtainAdvisorWithId(session.AdvisorId, this.context);
            session.Student = this.studentDal.ObtainStudentWithId(session.StudentId, this.context);

            return View(session);
        }
    }
}

code/AdvisementManager/StudentAdvisementManagerWebApp/Controllers/ScheduleAdvisementSessionController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Diagnostics;
using System.Linq;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using StudentAdvisementManagerWebApp.DAL;
using AdvisementManagerSharedLibrary.Models;
using AdvisementManagerSharedLibrary.Data;
using AdvisementManagerSharedLibrary.DAL;

namespace StudentAdvisementManagerWebApp.Controllers
{
    /// <summary>
    ///   The Schedule advisement session controller class
    /// </summary>
    public class ScheduleAdvisementSessionController : Controller
    {
        private readonly string departmentAdvisementHoldReason = "need to meet with dept advisor";

        private readonly string facultyAdvisementHoldReason = "need to meet with faculty advisor";

        public ApplicationDbContext context { get; }

        private readonly ScheduleAdvisementSessionDAL scheduleDal = new();

        private readonly StudentDal studentDal = new();

        private readonly AdvisorDAL advisorDal = new();

        private readonly HoldDAL holdDal = new();

        /// <summary>Initializes a new instance of the <see cref="ScheduleAdvisementSessionController" /> class.</summary>
        /// <param name="context">The context.</param>
        public ScheduleAdvisementSessionController(ApplicationDbContext context)
        {
            this.context = context;
            ViewBag.InvalidInputMessage = String.Empty;
        }

        /// <summary>Schedules the advisement session asynchronous.</summary>
        /// <param name="studentid">The studentid.</param>
        /// <param name="holdreason">The holdreason.</param>
        /// <param name="generaladvisorid">The generaladvisorid.</param>
        /// <param name="facultyadvisorid">The facultyadvisorid.</param>
        /// <returns>
        ///   The view to the schedule advisement session
        /// </returns>
        public IActionResult ScheduleAdvisementSession(int studentid, string holdreason, int generaladvisorid, int facultyadvisorid)
        {
            ScheduleAdvisementModel model = InitializeScheduleAdvismentModel(studentid);

            return View("../ScheduleAdvisementSession/ScheduleAdvisementSession", model);
        }

        /// <summary>
        ///     Initializes the schedule advisment model. 
        ///     Determines which advisor the student must meet with and gets there available times to display.
        /// </summary>
        /// <param name="student">The student.</param>
        /// <param name="holdreason">The holdreason.</param>
        /// <returns>
        ///   The schedule model
        /// </returns>
        private ScheduleAdvisementModel InitializeScheduleAdvismentModel(int studentId)
        {
            ScheduleAdvisementModel scheduleModel = new ScheduleAdvisementModel();
            Student student = this.studentDal.ObtainStudentWithId(studentId, this.context);

            scheduleModel.Student = student;

            if (student.Hold.Reason == this.departmentAdvisementHoldReason)
            {
                scheduleModel.Advisor = scheduleModel.Student.GeneralAdvisor;
            }
            else if (student.Hold.Reason == this.facultyAdvisementHoldReason)
            {
                scheduleModel.Advisor = scheduleModel.Student.FacultyAdvisor;
            }
            else
            {
                Debug.Print("Must add students that have standard reasons");
                scheduleModel.Advisor = scheduleModel.Student.GeneralAdvisor;
            }

            scheduleModel.SetAvailableSessionTimesListItems(scheduleModel.Student.GeneralAdvisor);
            return scheduleModel;
        }

        /// <summary>
        ///     Confirms the appointment is scheduled for a valid time and date,
        ///     returns Schedule view if not, schedules session on the database if so.
        /// </summary>
        /// <param name="studentid">The studentid.</param>
        /// <param name="advisorid">The advisorid.</param>
        /// <param name="date">The date.</param>
        /// <param name="time">The time.</param>
        /// <returns>
        ///     Redirections to the student home page, or
        ///     return Schedule view to get new dateTime.
        /// </returns>
        public IActionResult ConfirmAppointment(int? studentid, int? advisorid, DateTime date, TimeSpan time)
        {
            var sessionTime = date.AddMinutes(time.TotalMinutes);

            if (IsSessionTimeInTheFuture(sessionTime))
            {
                this.ScheduleSession(studentid.Value, advisorid.Value, sessionTime);
                return RedirectToAction("StudentHome", "Home");
            }

            ScheduleAdvisementModel scheduleModel = InitializeScheduleAdvismentModel(studentid.Value);

            ViewBag.InvalidInputMessage = "The appointment time cannot be in the past.";

            return View("../ScheduleAdvisementSession/ScheduleAdvisementSession", scheduleModel);
        }

        /// <summary>Determines if the appointment time is in the future</summary>
        /// <param name="sessionTime">The date of the session.</param>
        /// <returns>
        ///   bool, if the sessionTime is in the future or not.
        /// </returns>
        private bool IsSessionTimeInTheFuture(DateTime sessionTime)
        {
            return DateTime.Compare(sessionTime, DateTime.Now) > 0;
        }

        /// <summary>Schedules the advisement session to the database.</summary>
        /// <param name="studentid">The studentid.</param>
        /// <param name="advisorid">The advisorid.</param>
        /// <param name="sessionTime">The date of the session.</param>
        private void ScheduleSession(int studentId, int advisorId, DateTime sessionTime)
        {
            AdvisementSession session = new AdvisementSession
            {
                StudentId = studentId,
                AdvisorId = advisorId,
                Date = sessionTime,
                Completed = false,
                HoldId = this.holdDal.ObtainHold(studentId, this.context).Id
            };
            this.scheduleDal.ScheduleAdvisementSession(session, this.context);
        }
    }
}

code/AdvisementManager/StudentAdvisementManagerWebApp/Views/AdvisementSession/AdvisementSession.cshtml
@model AdvisementManagerSharedLibrary.Models.AdvisementSession

@{
    ViewData["Title"] = "Advisement Session";
}

<div class="text-center">
    <h2 class="display-3">Advisement Session</h2>
</div>

<div class="row">
    <div class="col">
        <div class="row">
            <label style="font-size:larger">Student: @Model.Advisor.FullName</label>
        </div>
        <div class="row">
            <label style="font-size:larger">Email: @Model.Advisor.Email</label>

        </div>
    </div>
    <div class="col">
        <div class="row">
            <label style="font-size:larger">Meeting Time: @Model.Date</label>
        </div>
        <div class="row">
            <label style="font-size:larger">Current Hold: @Model.Student.Hold.Reason</label>
        </div>
    </div>
</div>

<div class="row" style="padding-bottom:2em">
    <label class="text-center" style="font-size:larger">Advisor Notes</label>
    <textarea class="form-control" readonly cols="25" rows="7">@Model.Notes</textarea>
</div>

<div class="row">
    <a asp-controller="AdvisementSession" asp-action="AdvisementSessions" class="btn btn-secondary"
       asp-route-studentid="@Model.StudentId"
       asp-route-holdid="@Model.HoldId">
        Close
    </a>
</div>

code/AdvisementManager/StudentAdvisementManagerWebApp/Views/AdvisementSession/AdvisementSessions.cshtml
@model List<AdvisementSession>
@{
    ViewData["Title"] = "Advisement Sessions";
}

<div class="row">
    <table class="table table-bordered table-striped" style="margin:5px">
        <thead>
            <tr>
                <th>
                    Advisor
                </th>
                <th>
                    Meeting Time
                </th>
                <th>
                    Completed
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var meeting in Model)
            {
                <tr>
                    <td>
                        @meeting.Advisor.FullName
                    </td>
                    <td>
                        @meeting.Date
                    </td>
                    <td>
                        @meeting.Completed
                    </td>
                    <td>
                        <a class="btn btn-primary" asp-action="AdvisementSession" asp-route-id="@meeting.Id">View Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="row">
    <a class="btn btn-secondary" asp-controller="Home" asp-action="StudentHome">Close</a>
</div>

code/AdvisementManager/StudentAdvisementManagerWebApp/Views/AdvisementSession/ScheduleAdvisementSession.cshtml
@model ScheduleAdvisementModel
@{
    ViewBag.Title = "Schedule Advisement";
}

@section scripts{
    <script>
        function SetTime(value) {
            window.location.href = "ScheduleAdvisementSession?studentid=" + @Model.StudentId + "&studentholdid=" + @Model.StudentId + "&generaladvisorid=" + @Model.Student.generalAdvisorId + "&facultyadvisorid=" + @Model.Student.facultyAdvisorId + "&selecteddate=" + value;
        }
        window.addEventListener("load", function () {

            if (@Model.AvailableSessionTimes.Count == 0) {
                document.getElementById('submit_button').setAttribute("disabled", "disabled");
            } else {
                document.getElementById('submit_button').removeAttribute("disabled");
            }
        });
    </script>
}

<div class="container">

    <main>
        <form asp-action="ConfirmAppointment" method="post" class="form-horizontal">
            <div class="row">
                <label class="control-label col-sm-2">Student:</label>
                <input asp-for="Student" readonly
                       class="form-control col-sm-10" />
            </div>

            <input asp-for="StudentId" type="hidden" />
            <input asp-for="AdvisorId" type="hidden" />

            <div class="row">
                <label class="control-label col-sm-2">Advisor:</label>
                <input asp-for="Advisor" readonly
                       class="form-control col-sm-10" />
            </div>

            <div class="row">
                <tr>
                    <td>
                        <label class="control-label col-sm-2">Choose date:</label>
                    </td>
                    <td>
                        <input class="form-control col-sm-5" onchange="SetTime(this.value)" asp-for="Date" type="date" value="@Model.SelectedDate.Date.ToString("yyyy-MM-dd")" />
                    </td>
                </tr>
            </div>

            <div class="row">
                <label class="control-label col-sm-2">Choose time:</label>
                <select asp-for="Time" asp-items="Model.AvailableSessionTimes"></select>
            </div>

            <div class="row">
                <label class="text-danger" col-sm-2">@ViewBag.InvalidInputMessage</label>
            </div>

            <div class="col offset-sm-3 pl-0">

                <button type="submit" id="submit_button" class="btn btn-primary" disabled>
                    Schedule Meeting
                </button>

            </div>
        </form>
    </main>
</div>