code/AdvisementManager/AdvisementManagerWebApp/Controllers/HomeController.cs
using AdvisementManagerWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using AdvisementManagerWebApp.DAL;
using AdvisementManagerWebApp.Data;

namespace AdvisementManagerWebApp.Controllers
{
    /// <summary>
    ///   The home controllers class
    /// </summary>
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext context;

        private readonly Student studentModel;

        private readonly StudentDal studentDal = new();

        /// <summary>Initializes a new instance of the <see cref="HomeController" /> class.</summary>
        /// <param name="logger">The logger.</param>
        public HomeController(ApplicationDbContext context)
        {
            this.context = context;

            this.studentModel = this.studentDal.ObtainStudentWithId(1, this.context);
        }

        /// <summary>Students the home.</summary>
        /// <returns>
        ///   The current views model
        /// </returns>
        [HttpGet]
        public IActionResult StudentHome()
        {
            return View(this.studentModel);
        }

        /// <summary>Students the home.</summary>
        /// <param name="model">The model.</param>
        /// <returns>
        ///   The current views model
        /// </returns>
        [HttpPost]
        public IActionResult StudentHome(Student model)
        {
            return View(model);
        }

        /// <summary>Errors this instance.</summary>
        /// <returns>
        ///   The errors views model
        /// </returns>
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

code/AdvisementManager/AdvisementManagerWebApp/Controllers/ScheduleAdvisementSessionController.cs
using AdvisementManagerWebApp.Data;
using AdvisementManagerWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using AdvisementManagerWebApp.DAL;

namespace AdvisementManagerWebApp.Controllers
{
    /// <summary>
    ///   The Schedule advisement session controller class
    /// </summary>
    public class ScheduleAdvisementSessionController : Controller
    {
        private readonly ApplicationDbContext context;

        private readonly ScheduleAdvisementSessionDAL scheduleDal = new();

        private readonly StudentDal studentDal = new();

        private readonly AdvisorDAL advisorDal = new();

        /// <summary>Initializes a new instance of the <see cref="ScheduleAdvisementSessionController" /> class.</summary>
        /// <param name="context">The context.</param>
        public ScheduleAdvisementSessionController(ApplicationDbContext context)
        {
            this.context = context;
        }

        /// <summary>Schedules the advisement session asynchronous.</summary>
        /// <param name="studentid">The studentid.</param>
        /// <param name="holdreason">The holdreason.</param>
        /// <param name="generaladvisorid">The generaladvisorid.</param>
        /// <param name="facultyadvisorid">The facultyadvisorid.</param>
        /// <returns>
        ///   The view to the schedule advisement session
        /// </returns>
        public IActionResult ScheduleAdvisementSessionAsync(int studentid, string holdreason, int generaladvisorid, int facultyadvisorid)
        {
            Student student = this.studentDal.ObtainStudentWithId(studentid, this.context);

            ScheduleAdvisementModel model = initializeScheduleAdvismentModel(student, holdreason);

            return View("../ScheduleAdvisementSession/ScheduleAdvisementSession", model);
        }

        /// <summary>Initializes the schedule advisment model.</summary>
        /// <param name="student">The student.</param>
        /// <param name="holdreason">The holdreason.</param>
        /// <returns>
        ///   The schedule model
        /// </returns>
        private ScheduleAdvisementModel initializeScheduleAdvismentModel(Student student, string holdreason)
        {
            ScheduleAdvisementModel scheduleModel = new ScheduleAdvisementModel();
            scheduleModel.Student = student;

            if (holdreason == "Student must meet with general advisor")
            {
                scheduleModel.Advisor = student.GeneralAdvisor;
            }
            else if (holdreason == "Student must meet with faculty advisor")
            {
                scheduleModel.Advisor = student.FacultyAdvisor;
            }
            else
            {
                Debug.Print("Must add students that have standard reasons");
                scheduleModel.Advisor = student.GeneralAdvisor;
            }

            scheduleModel.SetAvailableSessionTimesListItems(student.GeneralAdvisor);
            return scheduleModel;
        }

        /// <summary>Confirms the appointment.</summary>
        /// <param name="studentid">The studentid.</param>
        /// <param name="advisorid">The advisorid.</param>
        /// <param name="date">The date.</param>
        /// <param name="time">The time.</param>
        /// <returns>
        ///   Redirections to the student home page
        /// </returns>
        public IActionResult ConfirmAppointment(int? studentid, int? advisorid, DateTime date, TimeSpan time)
        {
            AdvisementSession session = new AdvisementSession
            {
                StudentId = studentid.Value,
                AdvisorId = advisorid.Value,
                Date = date.AddMinutes(time.TotalMinutes),
                Completed = false
            };

            this.scheduleDal.ScheduleAdvisementSession(session, this.context);

            return RedirectToAction("StudentHome", "Home");
        }
    }
}

code/AdvisementManager/AdvisementManagerWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

code/AdvisementManager/AdvisementManagerWebApp/Views/Home/StudentHome.cshtml
@model Student
@{
    ViewBag.Title = "Advisement Manager Home";
}
<div class="container">
    <main>
        <form method="get" class="form-horizontal">
            <div class="row">
                <label class="control-label col-sm-2">First Name:</label>
                <input asp-for="FirstName" readonly
                       class="form-control col-sm-10" />
            </div>
            <div class="row">
                <label class="control-label col-sm-2">Last Name:</label>
                <input asp-for="LastName" readonly
                       class="form-control col-sm-10" />
            </div>
            <div class="row">
                <label class="control-label col-sm-2">Email:</label>
                <input asp-for="Email" readonly
                       class="form-control col-sm-10" />
            </div>
            <div class="row">
                <label class="control-label col-sm-2">General Advisor:</label>
                <input asp-for="GeneralAdvisor" readonly
                       class="form-control col-sm-10" />
            </div>
            <div class="row">
                <label class="control-label col-sm-2">Faculty Advisor:</label>
                <input asp-for="FacultyAdvisor" readonly
                       class="form-control col-sm-10" />
            </div>
            <div class="row">
                <label class="control-label col-sm-2">Advisement Status:</label>
                <input asp-for="Hold" readonly
                       class="form-control col-sm-10" />
            </div>
            <div class="row">
                <label class="control-label col-sm-2">Meeting:</label>
                <input asp-for="AdvisementSessionStatusMessage" readonly
                       class="form-control col-sm-10" />
            </div>

            @{
                if (Model.Meeting == null)
                {
                    <a asp-controller="ScheduleAdvisementSession" asp-action="ScheduleAdvisementSession"
                       class="btn btn-primary col-sm-5"
                       asp-route-studentid="@Model.Id"
                       asp-route-studentholdid="@Model.Hold.Id"
                       asp-route-generaladvisorid="@Model.GeneralAdvisor.Id"
                       asp-route-facultyadvisorid="@Model.FacultyAdvisor.Id">
                        ScheduleAdvisement
                    </a>
                }
            }
        </form>
    </main>
</div>